export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const MAIN_ROUTE = '/'
export const OGNE_ROUTE = '/Refractories'
export const DEV_ROUTE = '/Developers'
export const AGR_ROUTE = '/Users'
export const SEARCH_ROUTE = '/search'